### ISSUE TITLE
bug: This library is not at jcenter.

### ISSUE THREAD

**Issue by tankxxl** [amphiaraus/MaterialRadioGroup#1]
compile 'net.soulwolf.image:materialRadio:1.0.1'      error!!
![-1](https://cloud.githubusercontent.com/assets/1826540/9243922/a81b0b40-41c8-11e5-9c3a-7659ae67d32f.jpg)

**Comment by mapleqin** [comment]
@tankxxl I'm sorry, I will Group Id: compile 'net.soulwolf.widget:materialRadio:1.0.1' written
compile 'net.soulwolf.image:materialRadio:1.0.1', the inconvenience caused to you, please forgive me! It has been amended to correct it!
